[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin"
  to = "https://femvents-admin.netlify.app/admin"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://femvents-admin.netlify.app/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/host/*"
  to = "https://femvents-host.netlify.app/:splat"
  status = 200
  force = true